In [1]:
from Acesso import Login
from Moeda import Moeda
from Query import Query
import os
from datetime import datetime,timedelta
import pandas as pd

s=Login()

sql=Query(s.usuario,s.senha,s.database,s.server)

querys={

    'Pendente':

    """
    
    SELECT Origem,Situação,Pedido,NFe,[Tipo de Pedido],Tabelas,[Data de Emissão],[Data de Entrega],
	cli.[ID Cliente],cli.[Razão Social],cli.[Nome Fantasia],
	vend.[ID Vendedor],vend.[Nome Resumido],vend.Categoria,vend.DDD,vend.Telefone,sup.Equipe,
	sup.[ID Sup],sup.Supervisor,sup.[DDD Sup],sup.[Telefone Sup],sup.[ID Gerente],sup.Gerente,sup.[DDD Gerente],
	sup.[Telefone Gerente],
	prod.SKU,prod.Produto,prod.Fabricante,[Unid. VDA],[Qtde. VDA],[Valor VDA],[Total Venda]
	FROM netfeira.vw_targetestatistico vda
	INNER JOIN netfeira.vw_cliente cli ON vda.[ID Cliente]=cli.[ID Cliente]
	INNER JOIN netfeira.vw_vendedor vend ON vda.[ID Vendedor]=vend.[ID Vendedor]
	INNER JOIN netfeira.vw_supervisor sup ON vend.[ID Equipe]=sup.[ID Equipe]
	INNER JOIN netfeira.vw_produto prod ON vda.SKU=prod.SKU
    WHERE [ID Situação]='AB' AND [Data de Entrega]=CONVERT(DATETIME,CAST(GETDATE() AS DATE),101) 
    AND [Data de Emissão]=DATEADD(DAY,-1,CONVERT(DATETIME,CAST(GETDATE() AS DATE),101))
    AND [Tipo de Operação]<>'OUTROS' 
    
    """

}

In [2]:
df=sql.CriarTabela(kwargs=querys)

In [6]:
df['Pendente'].groupby(['ID Cliente','Razão Social','Nome Fantasia'],as_index=False).agg({'Total Venda':'sum'}).sort_values('Total Venda',ascending=False,ignore_index=True)

,ID Cliente,Razão Social,Nome Fantasia,Total Venda
0,10099,SONDA SUPERMERCADO EXPORTACAO E IMPORTAC,SONDA LOJA 11 AGUA B,10102.76
1,21359,SONDA SUPERMERCADO EXPORTACAO E IMPORTAC,SONDA RUDGE RAMOS,3613.34
2,10096,SONDA SUPERMERCADOS EXPORTACAO E IMPORTA,SONDA LOJA 16 POMPEI,2895.30
3,10107,SONDA SUPERMERCADOS EXPORTACAO E IMPORTA,SONDA LOJA 13 ABC PE,1996.12
4,22828,SONDA SUPERMERCADOS EXPORTACAO E IMPORTACAO S.A,SONDA LJ 1051 ROMANA,1101.60
5,27868,FIDES COMERCIO DE ALIMENTOS LTDA,FIDES VILA MASCOTE,395.58
6,25014,CATIA YURIE MIURA MACIULAITIS 28891816850,DELIVERY FESTA,211.08
7,23557,MERCADO IRMAO VIEIRA EIRELI,MERCADO IRMAO VIEIRA,117.50
8,24565,SEMPRE BOM DIA PRODUTOS ALIMENTICIOS EIRELI,MERCADO BOM DIA LOJ2,98.10