In [1]:
from ConectionSQL import SQL
import pandas as pd
from Tempo import DataHora

sql=SQL('Netfeira','sqlserver','MOINHO','192.168.0.252')

conectando=sql.ConexaoSQL()

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
data=DataHora()

data_atual=data.HoraAtual()

ano=data_atual.year

mes=data_atual.month

dia=data_atual.day

In [4]:
querys={
    
    'Produto':
    
    """
    
    SELECT * FROM netfeira.vw_produto
    
    """,
    
    'Cliente':
    
    """
    
    SELECT * FROM netfeira.vw_cliente cli
    
    """,
    
    'Segmento':
    
    """
    
    SELECT * FROM netfeira.vw_segmento
    
    
    """,
    
    'TargetEstatico':
    
    
    """
    
IF (MONTH(GETDATE())-1)=0

    SELECT * FROM netfeira.vw_targetestatico
    WHERE YEAR([Data de Faturamento])=YEAR(GETDATE()) AND MONTH([Data de Faturamento])=MONTH(GETDATE())
	UNION ALL
    SELECT * FROM netfeira.vw_targetestatico
    WHERE YEAR([Data de Faturamento])=YEAR(GETDATE())-1 AND MONTH([Data de Faturamento])=12

ELSE

    SELECT * FROM netfeira.vw_targetestatico
    WHERE YEAR([Data de Faturamento])=YEAR(GETDATE()) AND MONTH([Data de Faturamento]) BETWEEN MONTH(GETDATE())-1 AND MONTH(GETDATE())
    
    """,
    
    'TargetMargem':
    
    """
    
    SELECT * FROM netfeira.vw_targetmargem
    
    """
    
}

In [5]:
tabelas_df=dict()

for tabela,query in querys.items():
    
    tabelas_df[tabela]=pd.read_sql(query,conectando)    
    
    pass

In [6]:
round(round(tabelas_df['TargetMargem']['Margem Média'].mean(axis=0),4)*100,2)

34.34

In [7]:
tabelas_df['TargetEstatico'].columns

Index(['Data de Emissão', 'Data de Faturamento', 'Pedido', 'Nfe', 'ID Empresa',
       'ID Cliente', 'ID Vendedor', 'Tipo de Pedido', 'Tipo de Operação',
       'SKU', 'Qtde', 'Unid. VDA', 'Qtde VDA', 'Valor VDA', 'Total Geral',
       'Total Venda', 'Comissão R$', 'Margem Bruta R$', 'Cad Vendedor',
       'Situação', 'Peso Bruto KG', 'Peso Líquido KG'],
      dtype='object')

In [8]:
tabelas_df['Produto'].columns

Index(['SKU', 'Cód. Fabricante', 'Produto', 'Status', 'Fabricante',
       'Departamento', 'Seção', 'Categoria', 'Linha', 'Grupo de Produtos',
       'Grupo Indústria', 'Grupo de Meta', 'Grupo MCCAIN', 'Linha Fabrica',
       'Grupo de Promotores', 'Peso Liquido', 'Peso Bruto', 'Fator CX'],
      dtype='object')

In [9]:
tabelas_df['TargetEstatico']=tabelas_df['TargetEstatico'].merge(tabelas_df['Produto'],on='SKU',how='inner')[['Data de Emissão', 'Data de Faturamento', 'Pedido', 'Nfe', 'ID Empresa',
       'ID Cliente', 'ID Vendedor', 'Tipo de Pedido', 'Tipo de Operação',
       'SKU','Produto', 'Status', 'Fabricante',
       'Departamento', 'Seção', 'Categoria', 'Linha','Qtde', 'Unid. VDA', 'Qtde VDA', 'Valor VDA', 'Total Geral',
       'Total Venda', 'Comissão R$', 'Margem Bruta R$', 'Cad Vendedor',
       'Situação', 'Peso Bruto KG', 'Peso Líquido KG']]

In [10]:
tabelas_df['Cliente'].columns

Index(['ID Cliente', 'CNPJ', 'CNPJ Caracter', 'Razão Social', 'Nome Fantasia',
       'Tipo de Cliente', 'Status do Cliente', 'ID Segmento', 'Matriz',
       'Crédito', 'Data de Cadastro', 'Primeira Compra', 'Última Compra',
       'Dias Compra', 'Tabela', 'Condição de Pagto', 'Prazo Pagto',
       'Pagamento', 'CEP', 'Endereço', 'Bairro', 'Município', 'Numero',
       'Complemento', 'Região', 'UF', 'DDD', 'Contato'],
      dtype='object')

In [11]:
tabelas_df['Segmento'].columns

Index(['ID Segmento', 'Segmento', 'Canal'], dtype='object')

In [12]:
tabelas_df['Cliente']=tabelas_df['Cliente'].merge(tabelas_df['Segmento'],on='ID Segmento',how='inner')[['ID Cliente', 'CNPJ', 'CNPJ Caracter', 'Razão Social', 'Nome Fantasia',
       'Tipo de Cliente', 'Status do Cliente', 'Segmento', 'Canal', 'Matriz',
       'Crédito', 'Data de Cadastro', 'Primeira Compra', 'Última Compra',
       'Dias Compra', 'Tabela', 'Condição de Pagto', 'Prazo Pagto',
       'Pagamento', 'CEP', 'Endereço', 'Bairro', 'Município', 'Numero',
       'Complemento', 'Região', 'UF', 'DDD', 'Contato']]

In [13]:
tabelas_df['TargetEstatico'].columns

Index(['Data de Emissão', 'Data de Faturamento', 'Pedido', 'Nfe', 'ID Empresa',
       'ID Cliente', 'ID Vendedor', 'Tipo de Pedido', 'Tipo de Operação',
       'SKU', 'Produto', 'Status', 'Fabricante', 'Departamento', 'Seção',
       'Categoria', 'Linha', 'Qtde', 'Unid. VDA', 'Qtde VDA', 'Valor VDA',
       'Total Geral', 'Total Venda', 'Comissão R$', 'Margem Bruta R$',
       'Cad Vendedor', 'Situação', 'Peso Bruto KG', 'Peso Líquido KG'],
      dtype='object')

In [14]:
tabelas_df['TargetEstatico']=tabelas_df['TargetEstatico'].merge(tabelas_df['Cliente'],on='ID Cliente',how='inner')[['Data de Emissão', 'Data de Faturamento', 'Pedido', 'Nfe', 'ID Empresa',
       'ID Cliente', 'CNPJ', 'CNPJ Caracter', 'Razão Social', 'Nome Fantasia',
       'Tipo de Cliente', 'Status do Cliente', 'Segmento', 'Canal', 'Matriz',
       'Crédito', 'Data de Cadastro', 'Primeira Compra', 'Última Compra',
       'Dias Compra', 'Tabela', 'Condição de Pagto', 'Prazo Pagto',
       'Pagamento', 'CEP', 'Endereço', 'Bairro', 'Município', 'Numero',
       'Complemento', 'Região', 'UF', 'DDD', 'Contato','ID Vendedor', 'Tipo de Pedido', 'Tipo de Operação',
       'SKU', 'Produto', 'Status', 'Fabricante', 'Departamento', 'Seção',
       'Categoria', 'Linha', 'Qtde', 'Unid. VDA', 'Qtde VDA', 'Valor VDA',
       'Total Geral', 'Total Venda', 'Comissão R$', 'Margem Bruta R$',
       'Cad Vendedor', 'Situação', 'Peso Bruto KG', 'Peso Líquido KG']]

In [15]:
tabelas_df['TargetEstatico']

,Data de Emissão,Data de Faturamento,Pedido,Nfe,ID Empresa,ID Cliente,CNPJ,CNPJ Caracter,Razão Social,Nome Fantasia,Tipo de Cliente,Status do Cliente,Segmento,Canal,Matriz,Crédito,Data de Cadastro,Primeira Compra,Última Compra,Dias Compra,Tabela,Condição de Pagto,Prazo Pagto,Pagamento,CEP,Endereço,Bairro,Município,Numero,Complemento,Região,UF,DDD,Contato,ID Vendedor,Tipo de Pedido,Tipo de Operação,SKU,Produto,Status,Fabricante,Departamento,Seção,Categoria,Linha,Qtde,Unid. VDA,Qtde VDA,Valor VDA,Total Geral,Total Venda,Comissão R$,Margem Bruta R$,Cad Vendedor,Situação,Peso Bruto KG,Peso Líquido KG
0,2022-06-07,2022-06-10,404175,938701.0,1,9090,60992146000192,14,SUPERMERCADOS MADRID LTDA,SUPERMERCADOS MADRID,J,ATIVO,10 OU + CHK,AS,MADRID,NORMAL,2011-05-02,2011-05-02,2022-07-13,0.0,TABELA DE PREÇO,BOLETO BANCARIO 28 DIAS,28.0,BANCO,1226001.0,RUA MARTIM FRANCISCO,SANTA CECÍLIA,SÃO PAULO,777,None,VILA BUARQUE,SP,0,1.111111e+10,JULIODEL,VENDA STK EXCLUSIVO,VENDAS,9457,PÃO HOT DOG CORTE PARCIAL 3/4 63G ARYZTA(PCT X...,ATIVO,ARYZTA,CONGELADOS,PADARIA,PÃES DE HOT DOG,PÃES DE HOT DOG,-16.0,CX,-2.0,94.85,-189.70,-189.70,-0.95,-41.17,JULIODEL,DEVOLUÇÃO PARCIAL,-13.808,-12.0
1,2022-06-01,2022-06-01,402546,937054.0,1,9090,60992146000192,14,SUPERMERCADOS MADRID LTDA,SUPERMERCADOS MADRID,J,ATIVO,10 OU + CHK,AS,MADRID,NORMAL,2011-05-02,2011-05-02,2022-07-13,0.0,TABELA DE PREÇO,BOLETO BANCARIO 28 DIAS,28.0,BANCO,1226001.0,RUA MARTIM FRANCISCO,SANTA CECÍLIA,SÃO PAULO,777,None,VILA BUARQUE,SP,0,1.111111e+10,JULIODEL,VENDA STK EXCLUSIVO,VENDAS,9457,PÃO HOT DOG CORTE PARCIAL 3/4 63G ARYZTA(PCT X...,ATIVO,ARYZTA,CONGELADOS,PADARIA,PÃES DE HOT DOG,PÃES DE HOT DOG,-24.0,CX,-3.0,94.85,-284.55,-284.55,-1.42,-61.51,JULIODEL,CANCELADO,-20.712,-18.0
2,2022-06-01,2022-06-01,402910,937351.0,1,9090,60992146000192,14,SUPERMERCADOS MADRID LTDA,SUPERMERCADOS MADRID,J,ATIVO,10 OU + CHK,AS,MADRID,NORMAL,2011-05-02,2011-05-02,2022-07-13,0.0,TABELA DE PREÇO,BOLETO BANCARIO 28 DIAS,28.0,BANCO,1226001.0,RUA MARTIM FRANCISCO,SANTA CECÍLIA,SÃO PAULO,777,None,VILA BUARQUE,SP,0,1.111111e+10,JULIODEL,VENDA STK EXCLUSIVO,VENDAS,9457,PÃO HOT DOG CORTE PARCIAL 3/4 63G ARYZTA(PCT X...,ATIVO,ARYZTA,CONGELADOS,PADARIA,PÃES DE HOT DOG,PÃES DE HOT DOG,24.0,CX,3.0,94.85,284.55,284.55,1.42,61.51,JULIODEL,FATURADO,20.712,18.0
3,2022-06-07,2022-06-08,404175,938701.0,1,9090,60992146000192,14,SUPERMERCADOS MADRID LTDA,SUPERMERCADOS MADRID,J,ATIVO,10 OU + CHK,AS,MADRID,NORMAL,2011-05-02,2011-05-02,2022-07-13,0.0,TABELA DE PREÇO,BOLETO BANCARIO 28 DIAS,28.0,BANCO,1226001.0,RUA MARTIM FRANCISCO,SANTA CECÍLIA,SÃO PAULO,777,None,VILA BUARQUE,SP,0,1.111111e+10,JULIODEL,VENDA STK EXCLUSIVO,VENDAS,9457,PÃO HOT DOG CORTE PARCIAL 3/4 63G ARYZTA(PCT X...,ATIVO,ARYZTA,CONGELADOS,PADARIA,PÃES DE HOT DOG,PÃES DE HOT DOG,16.0,CX,2.0,94.85,189.70,189.70,0.95,41.17,JULIODEL,FATURADO,13.808,12.0
4,2022-06-14,2022-06-15,405891,940097.0,1,9090,60992146000192,14,SUPERMERCADOS MADRID LTDA,SUPERMERCADOS MADRID,J,ATIVO,10 OU + CHK,AS,MADRID,NORMAL,2011-05-02,2011-05-02,2022-07-13,0.0,TABELA DE PREÇO,BOLETO BANCARIO 28 DIAS,28.0,BANCO,1226001.0,RUA MARTIM FRANCISCO,SANTA CECÍLIA,SÃO PAULO,777,None,VILA BUARQUE,SP,0,1.111111e+10,JULIODEL,VENDA STK EXCLUSIVO,VENDAS,9457,PÃO HOT DOG CORTE PARCIAL 3/4 63G ARYZTA(PCT X...,ATIVO,ARYZTA,CONGELADOS,PADARIA,PÃES DE HOT DOG,PÃES DE HOT DOG,8.0,CX,1.0,94.85,94.85,94.85,0.47,20.58,JULIODEL,FATURADO,6.904,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28718,2022-07-11,2022-07-12,411886,945255.0,1,27263,17466373000236,14,3 BRASSEURS RESTAURANTE E CERVEJARIA ARTESANAL...,3 BRASSEURS RESTAURA,J,ATIVO,RESTAURANTE,FS,None,NORMAL,2022-02-21,NaT,2022-07-12,1.0,TABELA DE PREÇO,BOLETO BANCARIO 07 DIAS,7.0,BANCO,5422010.0,"RUA DOS PINHEIROS, 227",PINHEIROS,SÃO PAULO,227,,PINHEIROS,SP,11,3.532952e+07,MAYRAQS,VENDA DEMARCHI,VENDAS,1057,"CONG. BATATA MCCAIN 7MM IMP (2,250 KG)",ATIVO,MCCAIN,CONGELADOS,BATATAS CONGELADAS,BATATA CORTE FINO,BATATA 7MM,80.0,CX,10.0,249.60,2496.00,2496.00,4.99,622.40,MAYRAQS,FATURADO,180.000,180.0
28719,2022-07-07,2022-07-08,411270,944731.0,1,28169,32197578000176,14,TACOS MEXICANOS BAR E RESTAURANTE LTDA.,TACOS MEXICANOS,J,ATIVO,RESTAURANTE,FS,None,NORMAL,2022-07-07,NaT,2022-07-08,5.0,TABELA DE PREÇO,BOLETO BANCARIO 21 DIAS,21.0,BANCO,5421001.0,"RUA CUNHA GAGO, 623",PINHEIROS,SÃO PAULO,623,,PINHEIROS,SP,11,9.900566e+08,MARLENES,VENDA DEMARCHI,VENDAS,1057,"CONG. BATATA MCCAIN 7MM IMP (2,250 KG)",ATIVO,MCCAIN,CONGELADOS,BATATAS CONGELADAS,BATATA CORTE FINO,BATATA 7MM,4.0,UN,4.0,33.00,132.00,132.00,6.60,38.32,MARLENES,FATURADO,9.000,9.0
28720,2022-07-08,2022-07-09,411517,944841.0,1,28180,45317452000130,14,TDA LTDA,TDA LTDA,J,ATIVO,BAR/LANCHONETE,FS,None,NORMAL,2022-07-08,NaT,2022-07-09,4.0,TABELA DE PREÇO,A VISTA,1.0,DINHEIRO,4537010.0,"RUA CLODOMIRO AMAZONAS, 79",VILA NOVA CONCEIÇÃO,SÃO PAULO,79,,ITAIM BIBI,SP,21,9.825682e+08,MAYRAQS,VENDA DEMARCHI,VENDAS,1057,"CONG. BATATA MCCAIN 7MM IMP (2,250 KG)",ATIVO,MCCAIN,CONGELADOS,BATATAS CONGELADAS,BATATA CORTE FINO,BATATA 7MM,8.0,CX,1.0,261.60,261.60,261.60,0.52,74.25,MAYRAQS,FATURADO,18.000,18.0
28721,2022-07-05,2022-07-06,410397,944139.0,1,25892,29765487000185,14,LETS POKE VILA OLIMPIA RESTAURANTE LTDA,LETS POKE,J,ATIVO,RESTAURANTE,FS,None,NORMAL,2021-07-15,NaT,2022-07-06,7.0,TABELA DE PREÇO,BOLETO BANCARIO 07 DIAS,7.0,BANCO,4551090.0,"ALAMEDA RAJA GABAGLIA, 166",VILA OLÍMPIA,SÃO PAULO,166,,ITAIM BIBI,SP,11,2.768768e+07,FLASANTO,VENDA DEMARCHI,VENDAS,692,RASPA DE LIMAO ( 5KG ),ATIVO,DE MARCHI,CONGELADOS,POLPAS DE FRUTAS,RASPA,RASPA BALDE,2.0,UN,2.0,181.00,362.00,362.00,4.34,123.98,FLASANTO,FATURADO,10.000,10.0
28722,2022-07-13,2022-07-13,412334,945575.0,1,20541,53775862000152,14,INSTRUTHERM INSTRUMENTOS DE MEDICAO,INSTRUTHERM INSTRUME,J,ATIVO,FORNECEDOR,AS,None,NORMAL,2018-05-03,NaT,NaT,NaN,TABELA DE PREÇO,A VISTA,NaN,DINHEIRO,2911030.0,"RUA JORGE DE FREITAS, 264",VILA SANTA DELFINA,SÃO PAULO,264,,FREGUESIA DO O,SP,11,2.144280e+07,AVULSO,CONSERTO,OUTROS,987,TERMOMETRO INFRAVERMELHO OS : 180302,ATIVO,PADRÃO,EQUIPAMENTOS,MANUTENÇAO,MATERIAL DE USO,MATERIAL DE USO,1.0,UN,1.0,600.00,600.00,600.00,0.00,0.00,CLISEMCO,FATURADO,0.000,1.0

In [16]:
tabelas_df['TargetEstatico']=tabelas_df['TargetEstatico'].loc[tabelas_df['TargetEstatico']['Tipo de Operação']!='OUTROS']

In [17]:
if((mes-1)==0):
    
    ano-=1
    
    mes=12
    
    pass

else:
    
    mes_ant=mes-1
    
    pass

In [18]:
def Classificar(valor):
    
    if(valor<=80):
        
        tipo='A'
        
        pass
    
    elif(valor<=95):
        
        tipo='B'
        
        pass
    
    else:
        
        tipo='C'
        
        pass
    
    return tipo
    
    pass

In [19]:
fabric_df=tabelas_df['TargetEstatico'][['Fabricante','Total Venda']].loc[(tabelas_df['TargetEstatico']['Data de Faturamento'].dt.year==ano)&(tabelas_df['TargetEstatico']['Data de Faturamento'].dt.month==mes_ant)].groupby(['Fabricante'],as_index=False).sum()

fabric_df.sort_values('Total Venda',ascending=False,ignore_index=True,inplace=True)

total=round(fabric_df['Total Venda'].sum(),2)

indice=fabric_df.index.tolist()

fabric_df['Rank']=indice

fabric_df['Total Acumulado']=fabric_df['Rank'].apply(lambda info: fabric_df['Total Venda'].loc[fabric_df['Rank']<=info].sum())

fabric_df['Total Geral']=total

fabric_df['Rep %']=round(fabric_df['Total Acumulado']/fabric_df['Total Geral'],4)*100

fabric_df['Classificação']=fabric_df['Rep %'].apply(Classificar)

marca=fabric_df['Fabricante'].loc[fabric_df['Classificação']!='C'].tolist()

In [20]:
temp_df=pd.DataFrame()

for m in marca:
    
    linha_df=tabelas_df['TargetEstatico'][['Linha','Fabricante','Total Venda']].loc[(tabelas_df['TargetEstatico']['Data de Faturamento'].dt.year==ano)&(tabelas_df['TargetEstatico']['Data de Faturamento'].dt.month==mes_ant)&(tabelas_df['TargetEstatico']['Fabricante']==m)].groupby(['Linha','Fabricante'],as_index=False).sum()
   
    linha_df.sort_values('Total Venda',ascending=False,ignore_index=True,inplace=True)

    total=round(linha_df['Total Venda'].sum(),2)

    indice=linha_df.index.tolist()

    linha_df['Rank']=indice

    linha_df['Total Acumulado']=linha_df['Rank'].apply(lambda info: linha_df['Total Venda'].loc[linha_df['Rank']<=info].sum())

    linha_df['Total Geral']=total

    linha_df['Rep %']=round(linha_df['Total Acumulado']/linha_df['Total Geral'],4)*100

    linha_df.loc[~linha_df['Rep %'].isnull()]
    
    linha_df['Classificação']=linha_df['Rep %'].apply(Classificar)
    
    linha_df=linha_df.loc[linha_df['Classificação']!='C']
    
    temp_df=pd.concat([temp_df,linha_df],axis=0,ignore_index=True)
        
    pass

lista=temp_df[['Linha','Fabricante']].to_dict('records')

lista[1]

{'Linha': 'LEGUMES ATÉ 2,5KG', 'Fabricante': 'DE MARCHI'}

In [21]:
df=pd.DataFrame()

for i in range(0,len(lista)):
    
    linha=lista[i]['Linha']
    
    fabricante=lista[i]['Fabricante']
     
    prod_df=tabelas_df['TargetEstatico'][['SKU','Produto','Fabricante','Linha','Total Venda']].loc[(tabelas_df['TargetEstatico']['Data de Faturamento'].dt.year==ano)&(tabelas_df['TargetEstatico']['Data de Faturamento'].dt.month==mes_ant)&(tabelas_df['TargetEstatico']['Fabricante']==fabricante)&(tabelas_df['TargetEstatico']['Linha']==linha)].groupby(['SKU','Produto','Fabricante','Linha'],as_index=False).sum()

    prod_df.sort_values('Total Venda',ascending=False,ignore_index=True,inplace=True)

    total=round(prod_df['Total Venda'].sum(),2)

    indice=prod_df.index.tolist()

    prod_df['Rank']=indice

    prod_df['Total Acumulado']=prod_df['Rank'].apply(lambda info: prod_df['Total Venda'].loc[prod_df['Rank']<=info].sum())

    prod_df['Total Geral']=total

    prod_df['Rep %']=round(prod_df['Total Acumulado']/prod_df['Total Geral'],4)*100

    prod_df.loc[~prod_df['Rep %'].isnull()]
    
    prod_df['Classificação']=prod_df['Rep %'].apply(Classificar)
    
    prod_df=prod_df.loc[prod_df['Classificação']!='C']
    
    df=pd.concat([df,prod_df],axis=0,ignore_index=True)    
            
    pass

lista_codigo=df['SKU'].tolist()

In [22]:
base_df=tabelas_df['TargetEstatico'].loc[(tabelas_df['TargetEstatico']['SKU'].isin(lista_codigo))&(tabelas_df['TargetEstatico']['Data de Faturamento'].dt.year==ano)&(tabelas_df['TargetEstatico']['Data de Faturamento'].dt.month==mes)]

In [23]:
tabelas_df['TargetMargem']=tabelas_df['TargetMargem'][['SKU','Margem B','Margem F','Margem Média']]

df=tabelas_df['TargetMargem']

df['Margem B']=df['Margem B']*100

df['Margem F']=df['Margem F']*100

df['Margem Média']=df['Margem Média']*100

In [24]:
margens_df=base_df[['SKU','Produto','Fabricante','Linha','Total Venda','Margem Bruta R$']].loc[base_df['Situação']!='EM ABERTO'].groupby(['SKU','Produto','Fabricante','Linha'],as_index=False).sum()

margens_df['MG %']=margens_df.apply(lambda info: round(info['Margem Bruta R$']/info['Total Venda'],4)*100,axis=1)

In [25]:
margens_df.columns#.merge(tabelas_df['TargetMargem'],on='SKU',how='inner')

Index(['SKU', 'Produto', 'Fabricante', 'Linha', 'Total Venda',
       'Margem Bruta R$', 'MG %'],
      dtype='object')

In [93]:
mg_df=margens_df.merge(tabelas_df['TargetMargem'],on='SKU',how='inner')[['SKU', 'Produto', 'Fabricante', 'Linha', 'Total Venda',
       'Margem Bruta R$', 'MG %','Margem B','Margem F','Margem Média']]

mg_df['Status']=mg_df.apply(lambda info: 'SIM' if info['MG %']<info['Margem F'] else 'NÃO',axis=1)

mg_df['Descrição']=mg_df['SKU'].map(str) + ' - ' + mg_df['Produto'].map(str)

mg_df.loc[mg_df['Status']=='SIM']

,SKU,Produto,Fabricante,Linha,Total Venda,Margem Bruta R$,MG %,Margem B,Margem F,Margem Média,Status,Descrição
30,1054,"CONG. BATATA MCCAIN NOISETTES 2,5KG NAC",MCCAIN,BATATA MASSA,547.68,98.94,18.07,28.38,21.57,24.98,SIM,"1054 - CONG. BATATA MCCAIN NOISETTES 2,5KG NAC"
39,9439,"PÃO HB BRIOCHE 4"" CT (15X64G)",ARYZTA,PÃO HB ESPECIAL,1032.00,281.00,27.23,38.77,28.01,33.39,SIM,"9439 - PÃO HB BRIOCHE 4"" CT (15X64G)"
41,9461,PÃO HB MONACO CT C/ GERGELIM CXG (12X75G),ARYZTA,PÃO HB MONACO,270.03,78.33,29.01,38.78,29.02,33.90,SIM,9461 - PÃO HB MONACO CT C/ GERGELIM CXG (12X75G)
43,9491,PÃO HB PN10 TRAD C/GERGELIM ARYZTA FP (PCT 4UN...,ARYZTA,FLOWPACK,100.59,32.66,32.47,44.99,36.20,40.60,SIM,9491 - PÃO HB PN10 TRAD C/GERGELIM ARYZTA FP (...

In [27]:
margens_df=base_df[['SKU','Produto','Fabricante','Linha','Total Venda','Margem Bruta R$']].loc[(base_df['Situação']=='EM ABERTO')&(base_df['Data de Faturamento'].dt.day==dia)].groupby(['SKU','Produto','Fabricante','Linha'],as_index=False).sum()

margens_df['MG %']=margens_df.apply(lambda info: round(info['Margem Bruta R$']/info['Total Venda'],4)*100,axis=1)

In [94]:
mg_df=margens_df.merge(tabelas_df['TargetMargem'],on='SKU',how='inner')[['SKU', 'Produto', 'Fabricante', 'Linha', 'Total Venda',
       'Margem Bruta R$', 'MG %','Margem B','Margem F','Margem Média']]

mg_df['Status']=mg_df.apply(lambda info: 'SIM' if info['MG %']<info['Margem F'] else 'NÃO',axis=1)

mg_df['Descrição']=mg_df['SKU'].map(str) + ' - ' + mg_df['Produto'].map(str)

mg_df.loc[mg_df['Status']=='SIM']

,SKU,Produto,Fabricante,Linha,Total Venda,Margem Bruta R$,MG %,Margem B,Margem F,Margem Média,Status,Descrição
30,1054,"CONG. BATATA MCCAIN NOISETTES 2,5KG NAC",MCCAIN,BATATA MASSA,547.68,98.94,18.07,28.38,21.57,24.98,SIM,"1054 - CONG. BATATA MCCAIN NOISETTES 2,5KG NAC"
39,9439,"PÃO HB BRIOCHE 4"" CT (15X64G)",ARYZTA,PÃO HB ESPECIAL,1032.00,281.00,27.23,38.77,28.01,33.39,SIM,"9439 - PÃO HB BRIOCHE 4"" CT (15X64G)"
41,9461,PÃO HB MONACO CT C/ GERGELIM CXG (12X75G),ARYZTA,PÃO HB MONACO,270.03,78.33,29.01,38.78,29.02,33.90,SIM,9461 - PÃO HB MONACO CT C/ GERGELIM CXG (12X75G)
43,9491,PÃO HB PN10 TRAD C/GERGELIM ARYZTA FP (PCT 4UN...,ARYZTA,FLOWPACK,100.59,32.66,32.47,44.99,36.20,40.60,SIM,9491 - PÃO HB PN10 TRAD C/GERGELIM ARYZTA FP (...

In [68]:
base_df=tabelas_df['TargetEstatico'].loc[(tabelas_df['TargetEstatico']['Data de Faturamento'].dt.year==ano)&(tabelas_df['TargetEstatico']['Data de Faturamento'].dt.month==mes)]

canal_df=base_df[['Canal','Total Venda','Margem Bruta R$']].loc[(base_df['Tipo de Operação']!='OUTROS')].groupby('Canal',as_index=False).sum()

canal_df['MG %']=canal_df.apply(lambda info: round(info['Margem Bruta R$']/info['Total Venda'],4)*100,axis=1)

canal_df['MG %'].loc[canal_df['Canal']=='AS'].tolist()

canal_df['MG %'].loc[canal_df['Canal']=='FS'].tolist()

canal_df

  Canal  Total Venda  Margem Bruta R$   MG %
0    AS    697314.35        184272.96  26.43
1    FS    826748.54        277698.78  33.59

In [52]:
realizado=base_df[['Total Venda']].sum().tolist()

margem_mes=base_df[['Margem Bruta R$']].sum().tolist()

perc_mes=round(margem_mes[0]/realizado[0],4)*100

perc_mes

30.31

In [83]:
bonificacao=round(base_df['Total Geral'].loc[base_df['Tipo de Operação'].str.strip().isin(['BONIFICAÇÃO','AMOSTRA'])].sum(),2)

total=round(base_df['Total Geral'].loc[~base_df['Tipo de Operação'].str.strip().isin(['BONIFICAÇÃO','AMOSTRA'])].sum(),2)

perc_bonif=round(bonificacao/total,4)*100

perc_bonif

1.44